from src.lib.palettes.Align import Align
from src.lib.palettes.Cur import Cur
from src.lib.palettes.Dim import Dim
from src.lib.palettes.Font import Font
from src.lib.palettes.Img import Img
from src.lib.palettes.Keys import Keys
from src.lib.palettes.Rgb import Rgb
from src.lib.palettes.Scroll import Scroll
from src.lib.palettes.SelectionBehavior import SelectionBehavior
from src.lib.palettes.SpinButton import SpinButton
from src.lib.palettes.StyleBase import StyleBase
