from src.lib.palettes.PaAlign import PaAlign
from src.lib.palettes.PaArrowType import PaArrowType
from src.lib.palettes.PaAutoFormating import PaAutoFormating
from src.lib.palettes.PaButtonSymbols import PaButtonSymbols
from src.lib.palettes.PaCur import PaCur
from src.lib.palettes.PaDigitMode import PaDigitMode
from src.lib.palettes.PaDim import PaDim
from src.lib.palettes.PaDragDropMode import PaDragDropMode
from src.lib.palettes.PaDropAction import PaDropAction
from src.lib.palettes.PaEchoMode import PaEchoMode
from src.lib.palettes.PaFlow import PaFlow
from src.lib.palettes.PaFocusPolicy import PaFocusPolicy
from src.lib.palettes.PaFont import PaFont
from src.lib.palettes.PaFrameShadow import PaFrameShadow
from src.lib.palettes.PaFrameShape import PaFrameShape
from src.lib.palettes.PaGridStyle import PaGridStyle
from src.lib.palettes.PaImg import PaImg
from src.lib.palettes.PaInputMask import PaInputMask
from src.lib.palettes.PaInsertPolicy import PaInsertPolicy
from src.lib.palettes.PaKeys import PaKeys
from src.lib.palettes.PaLayoutDirection import PaLayoutDirection
from src.lib.palettes.PaMovement import PaMovement
from src.lib.palettes.PaPopupMode import PaPopupMode
from src.lib.palettes.PaProgressFormat import PaProgressFormat
from src.lib.palettes.PaRgb import PaRgb
from src.lib.palettes.PaScrollPolicy import PaScrollPolicy
from src.lib.palettes.PaSegmentStyle import PaSegmentStyle
from src.lib.palettes.PaSelectionBehavior import PaSelectionBehavior
from src.lib.palettes.PaSelectionMode import PaSelectionMode
from src.lib.palettes.PaShadow import PaShadow
from src.lib.palettes.PaSizeAdjustPolicy import PaSizeAdjustPolicy
from src.lib.palettes.PaSizePolicy import PaSizePolicy
from src.lib.palettes.PaStyleBase import PaStyleBase
from src.lib.palettes.PaTabPosition import PaTabPosition
from src.lib.palettes.PaTextFormat import PaTextFormat
from src.lib.palettes.PaTickPosition import PaTickPosition
from src.lib.palettes.PaToolButtonStyle import PaToolButtonStyle

# DataClass
from src.lib.palettes.DataClass import *