class PaInputMask:

    NO = ""
    LETTER_REQUIRED = "A"
    LETTER_NOT_REQUIRED = "a"
    LETTER_AND_NUMBER_REQUIRED = "N"
    LETTER_AND_NUMBER_NOT_REQUIRED = "n"
    NO_BLANK_REQUIRED = "X"
    NO_BLANK_NOT_REQUIRED = "x"
    NUMBER_REQUIRED = "9"
    NUMBER_NOT_REQUIRED = "0"
    HEXA_REQUIRED = "H"
    HEXA_NOT_REQUIRED = "h"
