from src.widgets.Slider import Slider
from src.widgets.TextEdit import TextEdit
from src.widgets.TrayIcon import TrayIcon
from src.widgets.TreeWidget import TreeWidget

from src.widgets import MyPushButton
from src.widgets import MyToolButton
from src.widgets import MyRadioButton
from src.widgets import MyCheckBox
from src.widgets import MyCommandLinkButton
from src.widgets import MyListView
from src.widgets import MyTreeView
from src.widgets import MyTableView
from src.widgets import MyColumnView
from src.widgets import MyUndoView
from src.widgets import MyListWidget
from src.widgets import MyTreeWidget
from src.widgets import MyTableWidget
from src.widgets import MyGroupBox
from src.widgets import MyScrollArea
from src.widgets import MyToolBox
from src.widgets import MyTabWidget
from src.widgets import MyStackedWidget
from src.widgets import MyFrame
from src.widgets import MyWidget
from src.widgets import MyDockWidget
from src.widgets import MyComboBox
from src.widgets import MyFontComboBox
from src.widgets import MyLineEdit
from src.widgets import MyTextEdit
from src.widgets import MyPlainTextEdit
from src.widgets import MySpinBox
from src.widgets import MyDoubleSpinBox
from src.widgets import MyTimeEdit
from src.widgets import MyDateEdit
from src.widgets import MyDateTimeEdit
from src.widgets import MyDial
from src.widgets import MyScrollBar
from src.widgets import MySlider
from src.widgets import MyLabel
from src.widgets import MyTextBrowser
from src.widgets import MyCalendarWidget
from src.widgets import MyLCDNumber
from src.widgets import MyProgressBar
from src.widgets import MyLine
